name: Deploy Project
on: [push, workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with: 
          repository: ${{github.repository}}
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with: 
          repository: ${{github.repository}}
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: drop
          path: ./dist
          overwrite: true
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
      - name: deploy project
        run: echo "deploying project"
      
